CREATE DATABASE BankSystemWebAppDB;
USE BankSystemWebAppDB;

CREATE TABLE Users(
	FirstName VARCHAR(20) NOT NULL,
	MiddleName VARCHAR(20),
	LastName VARCHAR(20) NOT NULL,
	SSN CHAR(10) NOT NULL UNIQUE,
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Pwd VARCHAR(255) NOT NULL
);
CREATE INDEX idx_SSN ON Users(SSN);
	
CREATE TABLE BankAccounts(
	Name VARCHAR(20) NOT NULL UNIQUE,
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Balance FLOAT NOT NULL DEFAULT 0,
	OwnerID INT FOREIGN KEY REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE INDEX idx_Name ON BankAccounts(Name);